### ISSUE TITLE
Temp reading doesn't respond

### ISSUE THREAD

**Issue by waelnaseeb** [NorthernWidget-Skunkworks/T9602_Library#2]
Hello guys,

I'm testing a T9602 sensor using Controllino MAXI. I applied the library and uploaded the code, the results are:
- Humidity measurements respond successfully and accurately.
- Temperature readings don't respond (stuck at -39.77).
I doubted the code, therefore I tried another code and library, same results!
I suspect either the sensor doesn't send a complete measurement cycle or I've got a faulty sensor. 
I appreciate your advices and suggestions.
The code I've applied is:

void setup() {

  // scan I2C sensors
  Serial.begin(9600); 
  Serial.println("Start I2C scanner ...");
  Serial.print("\r\n");
  byte count = 0;
  byte i = 0;

  Wire.begin();
  for (byte i = 8; i < 120; i++)
  {
    Wire.beginTransmission(i);
    if (Wire.endTransmission() == 0)
      {
      Serial.print("Found I2C Device: ");
      Serial.print(" (0x");
      Serial.print(i, HEX);
      Serial.println(")");
      count++;
      delay(1);
      }
  }
  // finish scan I2C sensors

}

void loop() {
  // This is the minimum amount of time to wait before
    // reading the sensor
    delay(5000);
    
  // Take one reading every (delay + time to take reading) seconds
  // and print it to the screen
    
    mySensor.updateMeasurements();

    //float sensor data
    float tempC = mySensor.getTemperature();
    float humid = mySensor.getHumidity();
    String reading = mySensor.getString();
    String header = mySensor.getHeader();
    
    //print sensor data to serial monitor
    Serial.print("float tempC: ");
    Serial.println(tempC);
    Serial.print("float humid: ");
    Serial.println(humid);
    Serial.print("String all readings: ");
    Serial.println(reading);
    Serial.print("String reading units: ");
    Serial.println(header);

}

Cheers

Wael

**Comment by awickert** [comment]
Hi Wael. On a quick glance, your code makes sense to me. A large negative number like typically indicates either a faulty I2C connection (but your humidity measurement works) or that some piece of hardware is disconnected or otherwise broken inside of the sensor itself (possibly relating to the raw analog measurement). I believe that because you tried another library, it makes sense for it to actually be the sensor. I will close this as such, but please feel free to reopen if you find that it is the library that is at fault.

**Comment by waelnaseeb** [comment]
Thanks a lot @awickert for your feedback, I appreciate it.
